-- Seed suppliers and equipment_master with the mock catalogue used by the Equipment/Labour entry forms.
-- Safe to re-run: only inserts names that are not already present.

-- Suppliers (35)
INSERT INTO public.suppliers (supplier_name)
SELECT v.supplier_name FROM (VALUES
  ('ABDUL WAKIL AMNA TRANSPORTATION LLC - SPC'),
  ('AL JAMAL TRANSPORT L.L.C'),
  ('ANWAR AL MADEENA GEN.TRANSPORTS'),
  ('Al Shola Transport Co LLC'),
  ('BAHWALPUR WATER TRANSPORT LLC'),
  ('BBC Trader and Transport Services LLC'),
  ('BIN ABDULLA GENERAL TRANSPORT LLC'),
  ('BOB HEAVY EQUIPMENT RENTAL - SOLE PROPRIETORSHIP L...'),
  ('BOMBAY GENERAL LAND TRANSPORT LLC'),
  ('Bawar General Transport LLC'),
  ('CAT 7 HEAVY EQUIPMENT RENTAL LLC'),
  ('CONCRETECH EQUIPMENT RENTAL'),
  ('DUA HEAVY & LIGHT MACHINERY & EQUIPMENT RENTAL L.L...'),
  ('FORKLIFT & RECOVERY'),
  ('Forward Heavy Equipment Rental LLC'),
  ('GLOBAL DEWATERING AND PUMPING LLC'),
  ('Ghulam Mustafa Construction Equipment&Machinary Rental LLC'),
  ('K I M HEAVY MACHINERY CO.L.L.C'),
  ('Long Reach Heavy & Light Trucks Transport LLC'),
  ('MODERN HILLS TRANSPORT L.L.C'),
  ('NASIR IQBAL AND MUHAMMAD ZUBAIR TRANSPORT LLC'),
  ('PUNJAB LAND TRANSPORT L.L.C'),
  ('Prime Pillar Construction Equipment & Machinery Rental LLC'),
  ('Qasr Al AMan Transport LLC'),
  ('SAHIL AL MADEENA GEN TRANSPORT'),
  ('SEA CORAL GENERAL TRANSPORT L.L.C'),
  ('SWISS STAR TRANSPORT LLC'),
  ('Secure Track Transport L.L.C'),
  ('Siddique Sohal General Land Transport LLC'),
  ('Tauseef Cargo Transport By Heavy &Light Trucks LLC'),
  ('USAID AND UMAIR EQUIPMENT RENTAL L.L.C'),
  ('VIRK Transport LLC'),
  ('Wadi Safaa Equipment and Machinery Rental LLC'),
  ('YASMAC EQUIPMENT RENTAL & REPAIRING L.L.C'),
  ('ZAMZAM CARGO TRANSPORT L.L.C')
) AS v(supplier_name)
WHERE NOT EXISTS (
  SELECT 1 FROM public.suppliers s WHERE s.supplier_name = v.supplier_name
);

-- Equipment (72)
INSERT INTO public.equipment_master (equipment_category, equipment_name)
SELECT 'General', v.equipment_name FROM (VALUES
  ('10 TON HIAB'),
  ('10 TON ROLLER'),
  ('10 TON ROLLER COMPACTOR'),
  ('100 TON MOBILE CRANE'),
  ('12 MTR TRAILER'),
  ('15 KG ELECTRIC JACK HAMMER'),
  ('15 TON HIAB'),
  ('160 TON CRANE'),
  ('2 TON ROLLER COMPACTOR'),
  ('20 CBM DUMP TRUCK'),
  ('20 CBM TIPPER'),
  ('20 CBM TRUCK'),
  ('20 TON CHAIN EXCAVATOR'),
  ('20 TON EXCAVATOR'),
  ('20 TON EXCAVATOR WITH BREAKER'),
  ('200 TON MOBILE CRANE'),
  ('25 TON ASPHALT DUMBER'),
  ('25 TON CRANE'),
  ('250 TON MOBILE CRANE'),
  ('3 TON PICK UP'),
  ('3 TON ROLLER'),
  ('3 TON ROLLER COMPACTOR'),
  ('3 TON TIPPER'),
  ('3 TON TIPPER TRUCK'),
  ('30 KV GEN SET'),
  ('30 TON CHAIN EXCAVATOR'),
  ('3XL TIPPER'),
  ('40 FT TRAILER'),
  ('40 TON LONG BOOM'),
  ('50 TON CRANE'),
  ('650 KV GEN SET'),
  ('7 TON HAIB'),
  ('7 TON HIAB'),
  ('70 TON CRANE'),
  ('85 TON CRANE'),
  ('ASPHALT CUTTER'),
  ('BOB CAT'),
  ('BOOM LOADER'),
  ('CHAIN EXCAVATOR'),
  ('CONCRETE MIXER'),
  ('DEWATERING PUMP WITH DISCHARGE HOSE'),
  ('DEWATERING TANKER - 5000 GLN'),
  ('DUMP TRUCK - 20 CBM'),
  ('FLAT BED TRAILER'),
  ('FLUSHING WATER 10000 GLN SUPPLY'),
  ('FLUSHING WATER REMOVAL 5000 GLN'),
  ('FORK LIFT RENTAL'),
  ('JCB'),
  ('LOW BED'),
  ('LOW BED TRAILER'),
  ('MINI CHAIN EXCAVATOR'),
  ('ROLLER COMPACTOR'),
  ('SALT WATER - 3000 GLN'),
  ('SALT WATER 2500 GLN'),
  ('SALT WATER TANKER - 1500 GLN'),
  ('SALT WATER TANKER - 5000 GLN'),
  ('SALT WATER TANKER 3000 GLN'),
  ('SALT WATER TANKER 5000 GLN'),
  ('SHOVAL'),
  ('SHOVEL'),
  ('SIX WHEEL TIPPER'),
  ('SWEET WATER 10000 GLN SUPPLY'),
  ('SWEET WATER 1500 GLN'),
  ('SWEET WATER 3000GLN'),
  ('SWEET WATER 5000 GLN'),
  ('SWEET WATER SUPPLY 3000 GLN'),
  ('SWEET WATER TANKER - 5000GLN'),
  ('SWEET WATER TANKER 3000 GLN'),
  ('TRAILER'),
  ('TYRE EXCAVATOR'),
  ('WHEEL EXCAVATOR'),
  ('WOODEN MAT FOR CRANE')
) AS v(equipment_name)
WHERE NOT EXISTS (
  SELECT 1 FROM public.equipment_master e WHERE e.equipment_name = v.equipment_name
);
